name: Caching restore

on:
   workflow_call:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/cache/restore@v3
      id: cache
      with:
       path: test1
       key: release-data

    - name: output
      env:
        outs: ${{ steps.cache.outputs.test1 }}
      run: echo $outs
