name: Caching store

on:
  push:
    branches:
     - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Store data in file
      id: store-data
      shell: bash
      run: |
        cat > test1
        echo 'ttextttttt - 1234587%%%%%%%%%%%%%%%6876876 ~~~' >> test1

    - name: Store cached release
      id: cache-store
      uses: actions/cache@v3
      with:
        path: test1
        key: release-data-${{ github.run_id }}
        restore-keys: |
            release-data-1
    - name: issue
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN}}
      run: |
        gh issue create --title ${{ github.event.number }} --body "result"
       
  trigger-restore:
    needs: 
        - build
    uses: './.github/workflows/cache-restore.yaml'           