name: Caching restore

on:
   workflow_call:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/cache/restore@v3
      id: cache
      with:
       path: test1
       key: release-data-${{ github.run_id }}

    - name: test1
      shell: bash
      run: cat test1 


    - name: test issue
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN}}
      run: |
        echo "ISSUE_NUM=$(gh issue list -S "${{github.event.number}} in:title" | awk '{split($0,a," "); print a[1]}')"
        gh issue comment $ISSUE_NUM -b "hello there !"
   