name: Caching store

on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Store data in file
      id: store-data
      shell: bash
      run: |
        touch test1
        echo 'ttextttttt ~~~' >> test1

    - name: Restore cached release
      id: cache-store
      uses: actions/cache@v3
      with:
        path: test1
        key: release-data

    
  trigger-restore:
    needs: 
        - build
    uses: './.github/workflows/cache-restore.yaml'           