name: Caching store

on:
  push:
    branches:
     - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Store data in file
      id: store-data
      shell: bash
      run: |
        cat > test1
        echo 'ttextttttt - 1234587%%%%%%%%%%%%%%%6876876 ~~~' >> test1

    - name: Store cached release
      id: cache-store
      uses: actions/cache@v3
      with:
        path: test1
        key: release-data-${{ github.run_id }}
        restore-keys: |
            release-data-1
    - name: issue
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN}}
      run: |
        echo ${{ github.event.number }}
        gh issue create --title ${{ github.event.number }} --body 'testing this'

  trigger-restore:
    needs: 
        - build
    uses: './.github/workflows/cache-restore.yaml'           


  script-run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # - name: 'run script'
    #   shell: bash
    #   run: |
    #     ./test.script.sh

    # - name : 'upload'
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: my-artifact
    #     path: "hello.out"  

    - name: 'branch name'
      env:
        pkg: "testing"
      shell: bash  
      run: |
          git fetch
          branch="auto-update/${{ env.pkg }}-v1.0.0"
          echo $branch
          echo "exists=$(git show-ref $branch)" >> GITHUB_OUTPUT
          echo "here=${{ env.exists }}"
          if [[ ! -z $exists ]]; then
            echo "delete========"
            git push origin --delete $branch  
          fi
          echo "creating branch"
          git checkout -b $branch


    - name : 'create file'
      env:
        pkg: "testing"
      run: |
         cat > testing


    - name : 'branch'
      env:
        pkg: "testing"
      run: |
         git config --global user.name "Anjana V"
         git config --global user.email "anjana.rv83@gmail.com"       
         echo "set config..pulling"  
         git add testing
         git commit -m "hello.out"
         git pull --rebase "auto-update/${{ env.pkg }}-v1.0.0"
         git push origin "auto-update/${{ env.pkg }}-v1.0.0"