  name: release-drafter
  on:
    pull_request:
     types:
       - opened
       - reopened
       - synchronize

  jobs:
    lint-release:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-go@v3
          with:
            go-version: 1.20
  #      - uses: golangci/golangci-lint-action@v3
    tagging:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: tagging
          id: tag_pkg
          shell: bash
          run: |
            chmod +x ./tools/tag.sh
            ./tools/tag.sh
        - name : commit tag
          needs: tag_pkg
          id: commit_tag
          shell: bash
          run: |
            git tag -a ${{ steps.tag_pkg.output.NEWTAG }} -m ${{ steps.tag_pkg.output.NEWTAG }}